name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js for Angular
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Angular dependencies and build
      run: |
        cd Frontend
        npm install
        npm run build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Flask dependencies
      run: pip install -r Backend/requirements.txt

  deploy:
      runs-on: ubuntu-latest
      needs: build
      if: success()

      steps:
      - name: Deploy to Render F
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"branch": "main"}' \
            https://api.render.com/v1/render/deployments